apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
spec:
  selector:
    matchLabels:
      app: hive-metastore
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      containers:
      - image: hive-metastore:3.0.0
        name: hive-metastore
        env:
          - name: MYSQL_ROOT_USER
            value: root
          - name: MYSQL_ROOT_PASSWORD
            value: password


