apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: ingestion
  name: ingestion
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ingestion
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/kube-app-net: "true"
        io.kompose.service: ingestion
    spec:
      containers:
        - args:
            - /opt/airflow/ingestion_dependency.sh
          command:
            - /bin/bash
          env:
            - name: AIRFLOW_DB
              value: ${AIRFLOW_DB:-airflow_db}
            - name: AIRFLOW__API__AUTH_BACKENDS
              value: airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session
            - name: AIRFLOW__CORE__EXECUTOR
              value: LocalExecutor
            - name: AIRFLOW__OPENMETADATA_AIRFLOW_APIS__DAG_GENERATED_CONFIGS
              value: /opt/airflow/dag_generated_configs
            - name: DB_HOST
              value: ${AIRFLOW_DB_HOST:-mysql}
            - name: DB_PASSWORD
              value: ${AIRFLOW_DB_PASSWORD:-airflow_pass}
            - name: DB_PORT
              value: ${AIRFLOW_DB_PORT:-3306}
            - name: DB_SCHEME
              value: ${AIRFLOW_DB_SCHEME:-mysql+pymysql}
            - name: DB_USER
              value: ${AIRFLOW_DB_USER:-airflow_user}
          image: docker.getcollate.io/openmetadata/ingestion:1.0.1
          name: openmetadata-ingestion
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /opt/airflow/dag_generated_configs
              name: ingestion-volume-dag-airflow
            - mountPath: /opt/airflow/dags
              name: ingestion-volume-dags
            - mountPath: /tmp
              name: ingestion-volume-tmp
      restartPolicy: Always
      volumes:
        - name: ingestion-volume-dag-airflow
          persistentVolumeClaim:
            claimName: ingestion-volume-dag-airflow
        - name: ingestion-volume-dags
          persistentVolumeClaim:
            claimName: ingestion-volume-dags
        - name: ingestion-volume-tmp
          persistentVolumeClaim:
            claimName: ingestion-volume-tmp
status: {}
