apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - image: minio:latest
        name: minio
        env:
          - name: MINIO_USER
            value: minio
          - name: MINIO_PASSWORD
            value: minio123


