apiVersion: v1
kind: PersistentVolume
metadata:
  name: metabase-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /data/metabase  # Adjust the path as needed