apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-configmap
data:
  jvm.config: |-
    -server
    -Xmx1G
    -XX:-UseBiasedLocking
    -XX:+UseG1GC
    -XX:G1HeapRegionSize=32M
    -XX:+ExplicitGCInvokesConcurrent
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:+ExitOnOutOfMemoryError
    -XX:-OmitStackTraceInFastThrow
    -XX:ReservedCodeCacheSize=256M
    -XX:PerMethodRecompilationCutoff=10000
    -XX:PerBytecodeRecompilationCutoff=10000
    -Djdk.attach.allowAttachSelf=true
    -Djdk.nio.maxCachedBufferSize=2000000
  config.properties.coordinator:
    coordinator=true
    node-scheduler.include-coordinator=true
    http-server.http.port=8080
    query.max-memory=5GB
    query.max-memory-per-node=1GB
    query.max-total-memory-per-node=2GB
    discovery.uri=http://trino:8080
    http-server.authentication.type=PASSWORD
  config.properties.worker:
    coordinator=false
    node-scheduler.include-coordinator=true
    http-server.http.port=8080
    query.max-memory=5GB
    query.max-memory-per-node=1GB
    query.max-total-memory-per-node=2GB
    discovery.uri=http://trino:8080
  password-authenticator.properties:
    password-authenticator.name=file
    file.password-file=etc/trino/password.db
  steampipe.properties:
    connector.name=postgresql
    connection-url=jdbc:postgresql://steampipe:9193/steampipe?ssl=false
    connection-user=steampipe
    connection-password=steampipe123
