apiVersion: v1
kind: Service
metadata:
  name: trino
  labels:
    app: trino
spec:
  ports:
    - name: https
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: trino-coordinator