apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-configmap
data:
  jvm.config: |-
    -server
    -Xmx1G
    -XX:-UseBiasedLocking
    -XX:+UseG1GC
    -XX:G1HeapRegionSize=32M
    -XX:+ExplicitGCInvokesConcurrent
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:+ExitOnOutOfMemoryError
    -XX:-OmitStackTraceInFastThrow
    -XX:ReservedCodeCacheSize=256M
    -XX:PerMethodRecompilationCutoff=10000
    -XX:PerBytecodeRecompilationCutoff=10000
    -Djdk.attach.allowAttachSelf=true
    -Djdk.nio.maxCachedBufferSize=2000000
  config.properties.coordinator:
    coordinator=true
    node-scheduler.include-coordinator=true
    http-server.http.port=8080
    query.max-memory=5GB
    query.max-memory-per-node=1GB
    query.max-total-memory-per-node=2GB
    discovery.uri=http://trino:8080
    http-server.authentication.type=PASSWORD
  config.properties.worker:
    coordinator=false
    node-scheduler.include-coordinator=true
    http-server.http.port=8080
    query.max-memory=5GB
    query.max-memory-per-node=1GB
    query.max-total-memory-per-node=2GB
    discovery.uri=http://trino:8080
  password-authenticator.properties:
    password-authenticator.name=file
    file.password-file=etc/trino/password.db
  hive-metastore.properties:
    connector.name=hive
    hive.metastore.uri=thrift://metastore:9083
    hive.metastore-timeout=130s
    hive.create-empty-bucket-files=true
    hive.allow-drop-table=true
    hive.max-partitions-per-scan=1000000
    hive.s3.endpoint=http://minio:9000
    hive.s3.path-style-access=true
    hive.s3.ssl.enabled=false
    hive.s3.max-connections=100
    hive.s3.aws-access-key=minio
    hive.s3.aws-secret-key=minio123
    hive.non-managed-table-writes-enabled=true
  iceberg.properties:
    connector.name=iceberg
    hive.metastore.uri=thrift://metastore:9083
    hive.metastore-timeout=130s
    hive.create-empty-bucket-files=true
    hive.allow-drop-table=true
    hive.max-partitions-per-scan=1000000
    hive.s3.endpoint=http://minio:9000
    hive.s3.path-style-access=true
    hive.s3.ssl.enabled=false
    hive.s3.max-connections=100
    hive.s3.aws-access-key=minio
    hive.s3.aws-secret-key=minio123
    hive.non-managed-table-writes-enabled=true
