apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: trino-worker
spec:
  serviceName: trino-worker
  replicas: 2
  selector:
    matchLabels:
      app: trino-worker
  template:
    metadata:
      labels:
        app: trino-worker
    spec:
      containers:
      - image: trinodb/trino:latest
        imagePullPolicy: Always
        name: trino
        ports:
          - containerPort: 8080
        env:
          - name: MYSQL_ROOT_USER
            value: root
          - name: MYSQL_ROOT_PASSWORD
            value: password
          - name: MINIO_ROOT_USER
            value: minio
          - name: MINIO_ROOT_PASSWORD
            value: minio123
        command: ["/usr/lib/trino/bin/run-trino"]
        args: ["-v"]
        volumeMounts:
          - mountPath: /home/trino/config/jvm.config
            name: trino-configmap-volume
            subPath: jvm.config
          #Coordinator
          - mountPath: /home/trino/config/config.properties.coordinator
            name: trino-configmap-volume
            subPath: config.properties.coordinator
          #Worker
          - mountPath: /home/trino/config/config.properties.worker
            name: trino-configmap-volume
            subPath: config.properties.worker
          #Plugins
          - mountPath: /home/trino/config/node.properties
            name: trino-configmap-volume
            subPath: node.properties
          - mountPath: /home/trino/config/hive-metastore.properties
            name: trino-configmap-volume
            subPath: hive-metastore.properties
          - mountPath: /home/trino/config/iceberg.properties
            name: trino-configmap-volume
            subPath: iceberg.properties
          - mountPath: /home/trino/config/mysql.properties
            name: trino-configmap-volume
            subPath: mysql.properties
      volumes:
        - name: trino-configmap-volume
          configMap:
            name: trino-configmap