apiVersion: v1
kind: PersistentVolume
metadata:
  name: openldap-pv
spec:
  capacity:
    storage: 1Gi  # Adjust the storage capacity as needed
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/data/openldap-pv"  # Adjust the host path as needed
