apiVersion: v1
kind: Service
metadata:
  name: ranger-usersync
  namespace: ranger
spec:
  selector:
    app: ranger-usersync
  ports:
    - protocol: TCP
      port: 6082
      targetPort: 6082
  type: ClusterIP # Change if needed (e.g., NodePort, LoadBalancer)
