openapi: 3.0.0
info:
  title: trino
  version: 1.0.0
servers:
  - url: http://localhost:8080
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
paths:
  /v1/statement:
    post:
      tags:
        - default
      summary: request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example: show catalogs
      parameters:
        - name: X-Trino-Original-User
          in: header
          schema:
            type: string
          example: Guest
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /v1/statement/queued/{relative_next_uri}:
    get:
      tags:
        - default
      summary: response-status
      security:
        - bearerAuth: []
      parameters:
        - name: relative_next_uri
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /v1/statement/executing/{relative_next_uri}:
    get:
      tags:
        - default
      summary: response-results
      security:
        - bearerAuth: []
      parameters:
        - name: relative_next_uri
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
