apiVersion: v1
kind: Service
metadata:
  name: redash
  labels:
    app: redash
spec:
  type: NodePort
  ports:
    - name: https
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: redash
