apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"meta.helm.sh/release-name":"openmetadata","meta.helm.sh/release-namespace":"default"},"creationTimestamp":"2023-05-28T20:36:13Z","labels":{"app.kubernetes.io/instance":"openmetadata","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"openmetadata","app.kubernetes.io/version":"1.0.2","helm.sh/chart":"openmetadata-1.0.3"},"name":"openmetadata","namespace":"default","resourceVersion":"187636","uid":"0cdb0ee9-2185-4dbd-8b77-4d7c45101ff5"},"spec":{"ports":[{"name":"http","nodePort":30585,"port":8585,"protocol":"TCP","targetPort":"http"},{"name":"http-admin","nodePort":30586,"port":8586,"protocol":"TCP","targetPort":"http-admin"}],"selector":{"app.kubernetes.io/instance":"openmetadata","app.kubernetes.io/name":"openmetadata"},"sessionAffinity":"None","type":"NodePort"},"status":{"loadBalancer":{}}}
    meta.helm.sh/release-name: openmetadata
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-05-28T20:36:13Z"
  labels:
    app.kubernetes.io/instance: openmetadata
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: openmetadata
    app.kubernetes.io/version: 1.0.2
    helm.sh/chart: openmetadata-1.0.3
  name: openmetadata
  namespace: default
  resourceVersion: "189065"
  uid: 0cdb0ee9-2185-4dbd-8b77-4d7c45101ff5
spec:
  clusterIP: 10.110.137.135
  clusterIPs:
  - 10.110.137.135
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 30585
    port: 8585
    protocol: TCP
    targetPort: http
  - name: http-admin
    nodePort: 30586
    port: 8586
    protocol: TCP
    targetPort: http-admin
  selector:
    app.kubernetes.io/instance: openmetadata
    app.kubernetes.io/name: openmetadata
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer:
    ingress:
    - hostname: localhost
