resources:
  - ../../../components/trino
configMapGenerator:
  - name: trino-datasource-configmap
    behavior: merge
      - trino-datasource-config/hive-metastore-mysql.properties
      - trino-datasource-config/iceberg.properties
      - trino-datasource-config/minio.properties
      - trino-datasource-config/steampipe-postgres.properties