resources:
  - ../../../components/trino
configMapGenerator:
  - name: trino-datasource-configmap
    behavior: merge
    files:
      - trino-datasource-config/hive_metastore_mysql.properties
      - trino-datasource-config/iceberg.properties
      - trino-datasource-config/minio.properties
      - trino-datasource-config/steampipe_postgres.properties