apiVersion: v1
kind: Service
metadata:
  name: minio-console
  labels:
    app: minio
spec:
  type: NodePort
  ports:
    - name: https
      port: 9001
      targetPort: 9001
      protocol: TCP
  selector:
    app: minio
