resources:
  - hive-metastore-deployment.yaml
configMapGenerator:
  - name: hive-metastore-config
    files:
      - hive-metastore-config/core-site.xml
      - hive-metastore-config/metastore-site.xml