apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: openmetadata-server
  name: openmetadata-server
spec:
  ports:
    - name: "8585"
      port: 8585
      targetPort: 8585
    - name: "8586"
      port: 8586
      targetPort: 8586
    - name: 8585-tcp
      port: 8585
      targetPort: 8585
    - name: 8586-tcp
      port: 8586
      targetPort: 8586
  selector:
    io.kompose.service: openmetadata-server
status:
  loadBalancer: {}
